Portfolio2/Cablissimo/controllers/client_article.py
#! /usr/bin/python
# -*- coding:utf-8 -*-
from flask import Blueprint, render_template, session, request, redirect
from connexion_db import get_db
from controllers.client_liste_envies import client_historique_add

client_article = Blueprint('client_article', __name__, template_folder='templates')


@client_article.route('/client/article/declinaisons')
def client_article_declinaisons():
    mycursor = get_db().cursor()
    id_article = request.args.get('id_article', None)
    selected_couleur = request.args.get('couleur')
    selected_longueur = request.args.get('longueur')

    if not id_article:
        return redirect('/client/index')

    sql = '''
    SELECT
        c.id_cable AS id_article,
        c.nom_cable AS nom,
        c.image_cable AS image,
        c.id_type_prise
    FROM
        cable c
    WHERE
        c.id_cable = %s
    '''
    mycursor.execute(sql, (id_article,))
    article = mycursor.fetchone()

    if not article:
        return redirect('/client/index')

    sql_declinaisons = '''
    SELECT
        dc.id_declinaison_cable AS id_declinaison,
        dc.prix_declinaison AS prix,
        dc.stock,
        coul.nom_couleur AS couleur,
        lg.nom_longueur AS longueur,
        coul.id_couleur,
        lg.id_longueur
    FROM
        declinaison_cable dc
    JOIN
        couleur coul ON dc.id_couleur = coul.id_couleur
    JOIN
        longueur lg ON dc.id_longueur = lg.id_longueur
    WHERE
        dc.id_cable = %s
    ORDER BY
        coul.nom_couleur, lg.nom_longueur
    '''
    mycursor.execute(sql_declinaisons, (id_article,))
    declinaisons = mycursor.fetchall()

    selected_declinaison = None
    if selected_couleur and selected_longueur:
        selected_couleur = int(selected_couleur)
        selected_longueur = int(selected_longueur)

        sql_selected_declinaison = '''
        SELECT
            dc.id_declinaison_cable AS id_declinaison,
            dc.prix_declinaison AS prix,
            dc.stock,
            coul.nom_couleur AS couleur,
            lg.nom_longueur AS longueur,
            coul.id_couleur,
            lg.id_longueur
        FROM
            declinaison_cable dc
        JOIN
            couleur coul ON dc.id_couleur = coul.id_couleur
        JOIN
            longueur lg ON dc.id_longueur = lg.id_longueur
        WHERE
            dc.id_cable = %s
            AND dc.id_couleur = %s
            AND dc.id_longueur = %s
        LIMIT 1
        '''
        mycursor.execute(sql_selected_declinaison, (id_article, selected_couleur, selected_longueur))
        selected_declinaison = mycursor.fetchone()

    return render_template(
        'client/boutique/declinaison_article.html',
        article=article,
        declinaisons=declinaisons,
        selected_couleur=selected_couleur,
        selected_longueur=selected_longueur,
        selected_declinaison=selected_declinaison
    )


@client_article.route('/client/index')
@client_article.route('/client/article/show')
def client_article_show():
    mycursor = get_db().cursor()
    id_client = session.get('id_user')

    if not id_client:
        return "Utilisateur non connecté", 401

    filter_word = session.get('filter_word', None)
    filter_prix_min = session.get('filter_prix_min', None)
    filter_prix_max = session.get('filter_prix_max', None)
    filter_types = session.get('filter_types', None)

    sql = '''
    SELECT
        c.id_cable AS id_article,
        c.nom_cable AS nom,
        c.image_cable AS image,
        MIN(dc.prix_declinaison) AS prix,
        SUM(dc.stock) AS stock_total,
        COUNT(dc.id_declinaison_cable) AS nb_declinaisons,
        c.id_type_prise,
        (SELECT COUNT(*) FROM commentaire WHERE id_cable = c.id_cable) AS nb_commentaires,
        (SELECT AVG(note) FROM note WHERE id_cable = c.id_cable) AS note_moyenne,
        (SELECT COUNT(*) FROM liste_envie WHERE cable_id = c.id_cable AND utilisateur_id = %s) AS liste_envie
    FROM
        cable c
    JOIN
        declinaison_cable dc ON c.id_cable = dc.id_cable
    WHERE
        1=1
    '''
    params = [id_client]

    if filter_word:
        sql += " AND c.nom_cable LIKE %s"
        params.append(f"%{filter_word}%")

    if filter_prix_min:
        sql += " AND dc.prix_declinaison >= %s"
        params.append(filter_prix_min)

    if filter_prix_max:
        sql += " AND dc.prix_declinaison <= %s"
        params.append(filter_prix_max)

    if filter_types:
        sql += " AND c.id_type_prise IN (%s)" % ",".join(["%s"] * len(filter_types))
        params.extend(filter_types)

    sql += " GROUP BY c.id_cable, c.nom_cable, c.image_cable, c.id_type_prise"
    sql += " ORDER BY c.nom_cable;"
    mycursor.execute(sql, params)
    articles = mycursor.fetchall()

    sql_types = '''
    SELECT id_type_prise AS id_type_article,
           nom_type_prise AS libelle
    FROM type_prise
    ORDER BY libelle;
    '''
    mycursor.execute(sql_types)
    types_article = mycursor.fetchall()

    sql_panier = '''
    SELECT 
        c.nom_cable AS nom_article, 
        dc.prix_declinaison AS prix, 
        dc.stock AS stock, 
        lp.quantite AS quantite, 
        dc.id_declinaison_cable AS id_declinaison_article,
        coul.nom_couleur AS libelle_couleur, 
        lg.nom_longueur AS libelle_taille, 
        coul.id_couleur AS id_couleur, 
        lg.id_longueur AS id_taille,
        (dc.prix_declinaison * lp.quantite) AS sous_total
    FROM declinaison_cable AS dc
    JOIN cable AS c ON dc.id_cable = c.id_cable
    JOIN ligne_panier AS lp ON dc.id_declinaison_cable = lp.id_declinaison_cable
    JOIN couleur AS coul ON dc.id_couleur = coul.id_couleur
    JOIN longueur AS lg ON dc.id_longueur = lg.id_longueur
    WHERE lp.id_utilisateur = %s;
    '''
    mycursor.execute(sql_panier, (id_client,))
    articles_panier = mycursor.fetchall()

    sql_prix_total = '''
    SELECT COALESCE(SUM(dc.prix_declinaison * lp.quantite), 0) AS prix_total
    FROM ligne_panier lp
    JOIN declinaison_cable dc ON lp.id_declinaison_cable = dc.id_declinaison_cable
    WHERE lp.id_utilisateur = %s;
    '''
    mycursor.execute(sql_prix_total, (id_client,))
    prix_total = mycursor.fetchone()['prix_total']

    return render_template(
        'client/boutique/panier_article.html',
        articles=articles,
        articles_panier=articles_panier,
        prix_total=prix_total,
        items_filtre=types_article
    )


@client_article.route('/client/article/details')
def client_article_details():
    id_article = request.args.get('id_article', type=int)
    if id_article is None:
        return redirect('/client/index')

    mycursor = get_db().cursor()
    id_client = session.get('id_user')

    if not id_client:
        return redirect('/client/index')

    # Ajouter l'article à l'historique
    client_historique_add(id_article, id_client)

    sql = '''
    SELECT
    c.id_cable AS id_article,
    c.nom_cable AS nom,
    c.description_cable AS description,
    c.blindage,
    c.fournisseur,
    c.image_cable AS image,
    tp.nom_type_prise AS type_prise,
    MIN(dc.prix_declinaison) AS prix_min,
    MAX(dc.prix_declinaison) AS prix_max,
    SUM(dc.stock) AS stock_total,
    COUNT(dc.id_declinaison_cable) AS nb_declinaisons,
    (SELECT AVG(note) FROM note WHERE id_cable = c.id_cable) AS note_moyenne,
    (SELECT COUNT(*) FROM note WHERE id_cable = c.id_cable) AS nb_notes,
    (SELECT COUNT(*) FROM liste_envie WHERE cable_id = c.id_cable AND utilisateur_id = %s) AS liste_envie
    FROM
        cable c
    JOIN
        type_prise tp ON c.id_type_prise = tp.id_type_prise
    JOIN
        declinaison_cable dc ON c.id_cable = dc.id_cable
    WHERE
        c.id_cable = %s
    GROUP BY
        c.id_cable, c.nom_cable, c.description_cable, c.blindage, c.fournisseur, c.image_cable, tp.nom_type_prise
    '''
    mycursor.execute(sql, (id_client, id_article))
    article = mycursor.fetchone()

    if not article:
        return redirect('/client/index')

    sql_commentaires = '''
    SELECT
        com.id_commentaire,
        com.commentaire,
        com.date_publication,
        com.id_cable as id_article,
        com.valider,
        u.login AS nom_utilisateur,
        u.id_utilisateur,
        com.id_commentaire_parent
    FROM
        commentaire com
    JOIN
        utilisateur u ON com.id_utilisateur = u.id_utilisateur
    WHERE
        com.id_cable = %s AND (com.valider = 1 OR com.id_utilisateur = %s)
    ORDER BY
        CASE 
            WHEN com.id_commentaire_parent IS NULL THEN com.date_publication
            ELSE (SELECT parent.date_publication FROM commentaire parent WHERE parent.id_commentaire = com.id_commentaire_parent)
        END DESC,
        CASE
            WHEN com.id_commentaire_parent IS NULL THEN 0
            ELSE 1
        END,
        com.date_publication ASC
    '''
    mycursor.execute(sql_commentaires, (id_article, id_client))
    commentaires = mycursor.fetchall()

    sql_note_user = '''
    SELECT note
    FROM note
    WHERE id_cable = %s AND id_utilisateur = %s
    '''
    mycursor.execute(sql_note_user, (id_article, id_client))
    note_user = mycursor.fetchone()

    sql_commandes = '''
    SELECT 
        COUNT(DISTINCT c.id_commande) AS nb_commandes_article
    FROM 
        commande c
    JOIN 
        ligne_commande lc ON c.id_commande = lc.id_commande
    JOIN 
        declinaison_cable dc ON lc.id_declinaison_cable = dc.id_declinaison_cable
    WHERE 
        c.id_utilisateur = %s AND dc.id_cable = %s
    '''
    mycursor.execute(sql_commandes, (id_client, id_article))
    commandes_articles = mycursor.fetchone()

    if not commandes_articles:
        commandes_articles = {'nb_commandes_article': 0}

    sql_nb_commentaires = '''
    SELECT 
        COUNT(*) AS nb_commentaires_total,
        SUM(CASE WHEN valider = 1 THEN 1 ELSE 0 END) AS nb_commentaires_total_valide,
        (SELECT COUNT(*) FROM commentaire WHERE id_cable = %s AND id_utilisateur = %s) AS nb_commentaires_utilisateur,

Portfolio2/Cablissimo/templates/client/boutique/_filtre.html
<form method="post"  action="/client/panier/filtre"  style="display: inline-block">
    <div class="form-group">
        <input name="filter_word"  type="text" placeholder="Recherche" size="10" class="form-control"
               value="{% if session['filter_word'] %}{{ session['filter_word'] }}{% endif %}"  >
    </div>
   {% if items_filtre is defined %}
    <div class="form-group">
        <h4>Types articles</h4>
        {% for item_filtre in items_filtre %}
        <input type="checkbox" name="filter_types" value="{{ item_filtre.id_type_article }}"
               {% set id_item = item_filtre.id_type_article | string %}
               {% if session['filter_types'] %}
{#                   {%  if idItem in session['filter_types'] %} checked  {% endif %} #}
                   {{ ' checked ' if (id_item in session['filter_types']) else '' }}
               {% endif %}
{#                https://stackoverflow.com/questions/58433775/how-to-access-the-value-of-each-checkbox-in-a-table-with-flask#}
            >  {{ item_filtre.libelle }}
            <br/>
        {% endfor %}
    </div>
    {% endif %}

    <div class="form-group">
        <h5>Prix :</h5>
         <input name="filter_prix_min"  type="text" placeholder="min"  size="3"
            value="{% if session['filter_prix_min'] %}{{ session['filter_prix_min'] }}{% endif %}" >

       <input name="filter_prix_max"  type="text" placeholder="max"  size="3"
             value="{% if session['filter_prix_max'] %}{{ session['filter_prix_max'] }}{% endif %}" >
    </div>
    <button type="submit" class="btn btn-primary" style="display: inline-block;">Filtrer</button>
</form>
{% if session['filter_word'] or session['filter_prix_max'] or session['filter_prix_min'] or session['filter_types']%}
<form  action="/client/panier/filtre/suppr"  style="display: inline-block; margin: 5px;"  method="post" >
<button class="btn btn-primary" > Supprimer filtre </button>
</form>
{% endif %}

Portfolio2/Cablissimo/templates/client/boutique/_panier.html
            <div class="col-7">
            {% if articles_panier | length >= 1 %}
                <h3>Liste des articles dans mon panier</h3>
                <table class="table table-hover table-responsive">
                    <tr>
                        <th style="width: 300px">Nom</th>
                        <th style="width: 50px">Quantité</th>
                        <th style="width: 50px">Prix</th>
                        <th style="width: 100px">Sous-Total</th>
                        <th style="width: 400px">Action</th>
                    </tr>
                    {% for item_panier in articles_panier %}
                        <tr>
                            <td>{{item_panier.nom_article}}
                            {% if item_panier.id_couleur is defined and item_panier.id_couleur != None and item_panier.id_couleur >1 %}
                                <small style="color: #6dcea2">({{ item_panier.libelle_couleur }})</small>
                            {% endif %}
                            {% if item_panier.id_taille is defined and item_panier.id_taille != None and item_panier.id_taille >1 %}
                                <small style="color: #d941c2">({{ item_panier.libelle_taille }})</small>
                            {% endif %}
                            </td>
                            <td>{{item_panier.quantite}}</td>
                            <td>{{item_panier.prix}}</td>
                            <td>{{ "{:,.2f} €".format((item_panier.prix * item_panier.quantite)) }}{#{(panier.article.prix * panier.quantite)|number_format(2) }#}</td>
                            <td>
                                <form action="/client/panier/add"  style="display: inline-block;"  method="post">
                                    <input type="hidden" name="id_declinaison_article" value="{{ item_panier.id_declinaison_article }}">
                                    <input type="hidden" name="quantite" value="1">
                                    <input type="hidden" name="id_article" value="{{ item_panier.id_article }}">
                                    <button class="btn btn-primary" > + </button>
                                </form>
                                <form action="/client/panier/delete"   style="display: inline-block;"  method="post">
                                    <input type="hidden" name="id_declinaison_article" value="{{ item_panier.id_declinaison_article }}">
                                    <input type="hidden" name="id_article" value="{{ item_panier.id_article }}">
                                    <button class="btn btn-primary" > - </button>
                                </form>

                                <form action="/client/panier/delete/line"  style="display: inline-block;"  method="post">
                                    <input type="hidden" name="id_declinaison_article" value="{{ item_panier.id_declinaison_article }}">
                                    <input type="hidden" name="id_article" value="{{ item_panier.id_article }}">
                                    <button class="btn btn-primary" >Supprimer</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}

                </table>
                    {% if validation is defined and validation == 1 %}
                        <a href="/client/article/show" class="btn btn-primary" >Continuer ma commande</a>
                    {% else %}
                    <form action="/client/panier/vider"  style="display: inline-block;"  method="post" >
                        <button class="btn btn-primary"  > Éffacer tout </button>
                    </form>
                    <form action="/client/commande/valide"  style="display: inline-block;"  method="post" >
                        <button class="btn btn-primary" > Passer ma commande </button>
                    </form>
                    {% endif %}
                    {% if prix_total %}
                    Total à payer : <strong>{{ "{:,.2f} €".format(prix_total) }}</strong>
                    {% endif %}

            {% endif %}
            </div>

Portfolio2/Cablissimo/templates/client/boutique/declinaison_article.html
{% extends "client/layout_client.html" %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1>{{ article.nom }}</h1>
            <div class="row">
                <div class="col-md-6">
                    {% if article.image %}
                        <img src="{{ url_for('static', filename='images/') }}{{ article.image }}" alt="{{ article.nom }}" class="img-fluid">
                    {% else %}
                        <img src="{{ url_for('static', filename='images/no_photo.jpeg') }}" alt="Pas d'image" class="img-fluid">
                    {% endif %}
                </div>
                <div class="col-md-6">
                    <h3>Choisissez votre déclinaison :</h3>
                    <form action="{{ url_for('client_article.client_article_declinaisons') }}" method="get">
                        <input type="hidden" name="id_article" value="{{ article.id_article }}">

                        <div class="form-group mb-3">
                            <label for="couleur">Couleur :</label>
                            <select name="couleur" id="couleur" class="form-control" required>
                                <option value="">-- Sélectionnez une couleur --</option>
                                {% set couleurs_vues = {} %}
                                {% for declinaison in declinaisons %}
                                    {% if declinaison.id_couleur not in couleurs_vues %}
                                        {% set _ = couleurs_vues.update({declinaison.id_couleur: true}) %}
                                        <option value="{{ declinaison.id_couleur }}" {% if selected_couleur == declinaison.id_couleur %}selected{% endif %}>
                                            {{ declinaison.couleur }}
                                        </option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group mb-3">
                            <label for="longueur">Longueur :</label>
                            <select name="longueur" id="longueur" class="form-control" required>
                                <option value="">-- Sélectionnez une longueur --</option>
                                {% set longueurs_vues = {} %}
                                {% for declinaison in declinaisons %}
                                    {% if declinaison.id_longueur not in longueurs_vues %}
                                        {% set _ = longueurs_vues.update({declinaison.id_longueur: true}) %}
                                        <option value="{{ declinaison.id_longueur }}" {% if selected_longueur == declinaison.id_longueur %}selected{% endif %}>
                                            {{ declinaison.longueur }}
                                        </option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary mb-3">
                            <i class="fas fa-search"></i> Afficher cette déclinaison
                        </button>
                    </form>

                    {% if selected_declinaison %}
                        <div class="alert alert-info mb-3">
                            Prix : {{ selected_declinaison.prix }} € | Stock disponible : {{ selected_declinaison.stock }}
                        </div>

                        <form action="/client/panier/add" method="post" id="form-ajout-panier">
                            <input type="hidden" name="id_declinaison_article" value="{{ selected_declinaison.id_declinaison }}">

                            <div class="form-group mb-3">
                                <label for="quantite">Quantité :</label>
                                <input type="number" name="quantite" id="quantite" class="form-control" min="1" max="{{ selected_declinaison.stock }}" value="1" required>
                            </div>

                            <button type="submit" class="btn btn-success mt-3" {% if selected_declinaison.stock <= 0 %}disabled{% endif %}>
                                <i class="fas fa-shopping-cart"></i> Ajouter au panier
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>

            <div class="mt-4">
                <h3>Toutes les déclinaisons disponibles :</h3>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Couleur</th>
                            <th>Longueur</th>
                            <th>Prix</th>
                            <th>Stock</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for declinaison in declinaisons %}
                            <tr>
                                <td>{{ declinaison.couleur }}</td>
                                <td>{{ declinaison.longueur }}</td>
                                <td>{{ declinaison.prix }} €</td>
                                <td>
                                    {% if declinaison.stock > 0 %}
                                        {{ declinaison.stock }}
                                    {% else %}
                                        <span class="text-danger">Rupture de stock</span>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if declinaison.stock > 0 %}
                                        <form action="/client/panier/add" method="post" class="d-inline">
                                            <input type="hidden" name="id_declinaison_article" value="{{ declinaison.id_declinaison }}">
                                            <input type="hidden" name="quantite" value="1">
                                            <button type="submit" class="btn btn-sm btn-success">
                                                <i class="fas fa-plus"></i> Ajouter
                                            </button>
                                        </form>
                                    {% else %}
                                        <button class="btn btn-sm btn-secondary" disabled>
                                            <i class="fas fa-plus"></i> Ajouter
                                        </button>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-4">
            {% include('client/boutique/_panier.html') %}
        </div>
    </div>

    <div class="mt-4">
        <a href="/client/article/show" class="btn btn-primary">
            <i class="fas fa-arrow-left"></i> Retour à la boutique
        </a>
    </div>
</div>
{% endblock %}

Portfolio2/Cablissimo/templates/client/boutique/panier_article.html
{#  articles_panier  : tableau de dictionnaires
        * dictionnaire : nom quantite prix article_id [stock]
        *
#}

{% extends "client/layout_client.html" %}
{% block body %}
    <div class="container">
        <div class="row align-self-right">
        {% include('client/boutique/_panier.html') %}
            <div class="col">
              <h3>Les filtres</h3>
              Articles dont le nom est composé par :<br>
                 {% include('client/boutique/_filtre.html') %}
            </div>
        </div>

        <div class="bg-light p-3">
            <h1>Les articles</h1>
        </div>

       <div class="row">
    {% for article in articles %}
        <div class="card col-4 mt-4 p-1">
            <div class="card-body border-dark rounded p-1">
                <a href="/client/article/details?id_article={{ article.id_article }}" >
                <h3 class="card-title">
                    <span style="color: #0b2e13">{{ article.nom }}</span><br>
                    {{ article.prix }}
                    €
                </h3>
                     {%  if article.image is not none %}
                        <img class="card-img-top rounded mx-auto d-block"  style="width:100px;height:100px"  src="/static/images/{{ article.image }}"  alt="image  de {{ article.nom }}" >
                    {% else %} <img class="card-img-top rounded mx-auto d-block"   style="width:100px;height:100px"   src="/static/images/no_photo.jpeg"  alt="image  de {{ article.nom }}" >
                    {% endif %}
                    <hr>
                </a>
                <div class="row">
                    {% if article.stock_total > 0 %}
                        <form action="/client/article/declinaisons" method="get" class="col-5">
                            <input type="hidden" name="id_article" value="{{ article.id_article }}">
                            <div class="input-group">
                                <button class="btn btn-success" id="button-addon1">
                                <i class="fas fa-shopping-cart">Ajouter</i>
                                </button>
                            </div>
                        </form>
                    {% endif %}
                    <div class="col-2 align-content-end">
                        {% if article.liste_envie is defined %}
                            {%if article.liste_envie == 1 %}
                                <a href="/client/envie/add?id_article={{ article.id_article }}" style="text-decoration: none">💛</a>
                            {% else %}
                                <a href="/client/envie/add?id_article={{ article.id_article }}" style="text-decoration: none">🤍</a>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="card-footer">
                {% if article.stock_total > 0 %}
                    <small class="text-muted">Stock total disponible : {{ article.stock_total }} </small>
                    {% if article.nb_declinaisons is defined %}
                        <small class="text-muted">({{ article.nb_declinaisons }} déclinaisons)</small>
                    {% endif %}
                {% else %}
                    <small class="text-muted">Article momentanément indisponible</small>
                {% endif %}
                <br>
                {% if article.note_moyenne is not none %}
                    <a href="/client/article/details?id_article={{ article.id_article }}" >
                        <span style="color: #3A7734"> Note : {{ "{:,.1f}".format(article.note_moyenne) }}</span>
                    </a>
                {% endif %}
                {% if article.nb_commentaires > 0 %}
                    <a href="/client/article/details?id_article={{ article.id_article }}" >
                        <span style="color: #3A7734">({{ article.nb_commentaires }} avis)</span>
                    </a>
                {% endif %}
            </div>
        </div>
    {% endfor %}
</div>
    </div>
{#    {{ articles | pprint }}#}
{% endblock %}

Portfolio2/Cablissimo/templates/client/boutique/panier_validation_adresses.html
{% extends "client/layout_client.html" %}
{% block body %}
    <div class="container">
        <div class="row align-self-right">
            {% include('client/boutique/_panier.html') %}
        </div>
        <div class="row">
             <br>
            <a href="/client/coordonnee/show" class="btn btn-secondary mt-5 col-2"> ajouter une adresse (livrable 2)</a>
            <form action="/client/commande/add"  style="display: inline-block;"  method="post" >
            {% if adresses | length > 0 %}
                <br>
                    <h4>Choisisser l'adresse de livraison</h4>
                    <select  name="id_adresse_livraison" name="adresse_livraison" required  class="form-select">
                        <option value="">Sélectionner l'adresse de facturation</option>
                        {% for adresse  in adresses %}
                             <option value="{{ adresse.id_adresse }}"
                             {% if adresse.est_favorite == 1 %}
                                 selected
                             {% endif %}
                             >{{ adresse.nom_client }} ({{ adresse.code_postal }})
                                 {{ adresse.ville }} - {{ adresse.rue }}
                             {% if adresse.est_favorite == 1 %}
                                 (💛)
                             {% endif %}
                             </option>
                        {% endfor %}
                    </select>
                    <br>

                    <h4>Choisisser l'adresse de facturation</h4>
                    adresse de facturation identique <input type="checkbox" name="adresse_identique" value="adresse_identique" id="adresse_identique" onclick="identique()">
                <br>
                    <select  id="id_adresse_facturation" name="id_adresse_facturation" required class="form-select">
                        <option value="">Sélectionner l'adresse de livraison</option>
                        {% for adresse  in adresses %}
                             <option value="{{ adresse.id_adresse }}"
                             {% if adresse.est_favorite == 1 %}
                                 selected
                             {% endif %}
                             >{{ adresse.nom_client }} ({{ adresse.code_postal }})
                                 {{ adresse.ville }} - {{ adresse.rue }}
                             {% if adresse.est_favorite == 1 %}
                                 (💛)
                             {% endif %}
                             </option>
                        {% endfor %}
                    </select>
                {%  else %}
                    Il faut une adresse de livraison et de facturation pour valider la commande (livrable 2)
                    <a href="/client/coordonnee/show"  class="btn btn-primary">Ajouter une adresse (livrable 2)</a>
                {% endif %}
                <br>
                <button class="btn btn-primary mt-4" > Passer ma commande </button>
            </form>
        </div>
    </div>

    <script>
    function identique(){
	if(document.getElementById('adresse_identique').checked == true)
        {
        document.getElementById("id_adresse_facturation").style.display = 'none';
        document.getElementById("id_adresse_facturation").required = false;
        }
        else
        {
        document.getElementById("id_adresse_facturation").style.display = 'block';
        document.getElementById("id_adresse_facturation").required = true;
        }
    };
    </script>
{% endblock %}